# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShoplazzaCli < Formula
  desc "The official CLI for Shoplazza Open Platform"
  homepage "https://github.com/Shoplazza/shoplazza-cli"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Shoplazza/shoplazza-cli/releases/download/v2.0.1/shoplazza-cli-2.0.1-darwin-amd64.tar.gz"
      sha256 "0e551e8892900a89fb32fe398dd0671ae631505405b1dd73f16e18d46fd6b7d6"

      define_method(:install) do
        bin.install "shoplazza"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Shoplazza/shoplazza-cli/releases/download/v2.0.1/shoplazza-cli-2.0.1-darwin-arm64.tar.gz"
      sha256 "5923bf78ebe1cd2f4794b73d19ee74f44f80f160a005658ff8e434bd175339dd"

      define_method(:install) do
        bin.install "shoplazza"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shoplazza/shoplazza-cli/releases/download/v2.0.1/shoplazza-cli-2.0.1-linux-amd64.tar.gz"
      sha256 "dcd5d2d04516032515510af7339ae4bc71840eec2c98d8027115c83da5c2ef1a"
      define_method(:install) do
        bin.install "shoplazza"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shoplazza/shoplazza-cli/releases/download/v2.0.1/shoplazza-cli-2.0.1-linux-arm64.tar.gz"
      sha256 "987db8cf97d1c95ac2cce86790f5f86f51902baab3e4f89e51940bbc769056de"
      define_method(:install) do
        bin.install "shoplazza"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/shoplazza --version")
  end
end
